[cursor]
thickness = 0.2
unfocused_hollow = true

[env]
decorations = "none"

[window]
dynamic_padding = true
option_as_alt = "Both"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "None"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = 11
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = 12
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = 12
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = 13
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = 13
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001b[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001b[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/gruvbox_dark.toml"
    # "~/.config/alacritty/gruvbox_light.toml"
]
